//tealium universal tag - utag.65 ut4.0.201810170655, Copyright 2018 Tealium.com Inc. All Rights Reserved.
function setMediasetitUserId(){if(typeof gigya!='undefined'){console.log("TAG MANAGER LOGIN -> lancio getAccountInfo");gigya.accounts.getAccountInfo({callback:setMediasetitUserIdCallback,include:'loginIDs,profile,data'});}else{console.log("TAG MANAGER LOGIN -> gigya non definito all'interno della funzione di setting, non verrà calcolato l'uid utente");if(utag_data!=null){utag_data.mediasetit_user_id_calculated="true";}else{console.log("TAG MANAGER LOGIN -> utag_data non definito all'interno della funzione di setting, errore non previsto");}}}
function setMediasetitUserIdCallback(response){console.log("TAG MANAGER LOGIN -> callback getAccountInfo. errorCode da response: "+response.errorCode);var tm_UIDSignature='';var tm_signatureTimestamp='';var tm_parameter='';var tm_UID='';if(utag_data!=null){utag_data.mediasetit_user_id_calculated="true";if(response.errorCode==0){tm_UID=response['UID'];tm_UIDSignature=response['UIDSignature'];tm_signatureTimestamp=response['signatureTimestamp'];console.log('TAG MANAGER LOGIN -> utente loggato. UID: '+tm_UID+" privacy: "+response['data'].privacy_v1_1);utag_data.user_username=response['username'];utag_data.user_status="a";utag_data.login="loggato";if(typeof response['data'].privacy_v1_1!='undefined'&&response['data'].privacy_v1_1=="true"){utag_data.mediasetit_user_id=tm_UID;utag_data.user_email=response['profile'].email;tm_parameter='UID='+tm_UID+'&UIDSignature='+tm_UIDSignature+'&signatureTimestamp='+tm_signatureTimestamp;console.log('TAG MANAGER LOGIN -> utente con privacy a true');utag_data.user_crm_id_1=tm_UID;if(typeof $!='undefined'){$.getJSON('https://api.mediaset.net/Customer/hash.jsp?callback=?&'+tm_parameter,function(data){try{utag_data.id=data.x2;utag_data.user_gender=data.x1;utag_data.user_age_range=data.x3;utag_data.user_province=data.x4;}catch(er){}
__callUTAGView();});}else{__callUTAGView();}}else{console.log('TAG MANAGER LOGIN -> utente con privacy a false');__callUTAGView();}}else{utag_data.mediasetit_user_id="";console.log('TAG MANAGER LOGIN -> utente non loggato');__callUTAGView();}
__callUTAGView();console.log('TAG MANAGER LOGIN -> conclusione callback getAccountInfo.');}}
if(utag_data!=null){console.log("TAG MANAGER -> inizio calcolo uid utente");utag_data.mediasetit_user_id="";utag_data.user_status="b";utag_data.ua=window.navigator.userAgent;utag_data.login="no-loggato";__callUTAGView();__callUTAGView();utag_data.cookie_type_wt=((/^((?!chrome|android).)*safari|fbios/i.test(window.navigator.userAgent))?"1":"3");__callUTAGView();}else{console.log("TAG MANAGER -> nessun data layer definito");}
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("65","mediaset.med.meteo.mediaset.it");}catch(error){utag.DB(error);}
